# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PhotoBombers' do
    pod 'ReactiveCocoa', '2.4.7'
    pod 'SimpleAuth/Instagram', '0.3.6'
end
